server:
  port: 8080
  servlet:
    context-path: /commend

spring:
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1
        ## 连接池中的最大空闲连接
        max-idle: 8
        ## 连接池中的最小空闲连接
        min-idle: 0
    ## 连接超时时间（毫秒）
    timeout: 5000

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.51.109.246:3306/springboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
  jackson:
    serialization:
      indent-output: true
logging:
  level:
    com.lee.commend: debug
